palette = true
no_color = false
theme = "Boron"
color = "Cyan"
custom_ascii = "/opt/ascii/arch"
no_separator = true
no_bar_delimiter = true
no_title = false
no_ascii = false
no_box = false 
bar = true
random_color = false
random_sep_color = false
short_uptime = false
long_shell = true
small_ascii = false
box_inner_margin_x = 1
box_inner_margin_y = 0
